### ISSUE TITLE
Generate Tetradic Palette

### ISSUE THREAD

**Issue by tavyandy97** [isarvindone/Matercolors#20]
Great package @isarvindone !
Would like to contribute to it by working on the task of generating a tetradic palette

**Comment by isarvindone** [comment]
Hello @tavyandy97! That's great!

Let me know when you have a pull request or if have any questions!

**Comment by tavyandy97** [comment]
Hey @isarvindone ,
Have raised a PR for the issue - https://github.com/isarvindone/Matercolors/pull/21

Please review it whenever you get time and lemme know if any changes are required 🍻

**Comment by tavyandy97** [comment]
@isarvindone Please do! Thanks for taking the time out 😊

**Comment by tavyandy97** [comment]
Hey @isarvindone,
Got the time to review the PR?

**Comment by tavyandy97** [comment]
Merged https://github.com/isarvindone/Matercolors/pull/21
